"""empty message

Revision ID: 100769551ef5
Revises: 11d2d4d6de27
Create Date: 2020-08-20 14:25:44.334202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '100769551ef5'
down_revision = '11d2d4d6de27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usercontent', sa.Column('modify_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usercontent', 'modify_date')
    # ### end Alembic commands ###
