"""empty message

Revision ID: c02fe550159a
Revises: 06c5371b6606
Create Date: 2020-08-21 11:06:38.716435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c02fe550159a'
down_revision = '06c5371b6606'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usercontent_like_voter',
    sa.Column('usercontent_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usercontent_id'], ['usercontent.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usercontent_id', 'user_id')
    )
    op.create_table('comment_like_voter',
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('comment_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment_like_voter')
    op.drop_table('usercontent_like_voter')
    # ### end Alembic commands ###
